export const theme = {
  colors: {
    primaryColor: '#0a1128',
    secondaryColor: '#dc143c',
    white: '#ffffff',
  },
  font: {
    family: {
      default: "'Open Sans', sans-serif",
      secondary: "font-family: 'Montserrat', sans-serif;",
    },
    sizes: {
      xsmall: '8rem',
      small: '1.6rem',
      medium: '2.4rem',
      large: '3.2rem',
      xlarge: '4.0rem',
      xxlarge: '4.8rem',
      huge: '5.6rem',
      xhuge: '6.4rem',
    },
  },
  media: {
    lteMedium: '(max-width: 768px)',
  },
  paddings: {
    xsmall: '0.4rem',
    small: '0.8rem',
    medium: '1.2rem',
    large: '1.6rem',
    xlarge: '2rem',
    xxlarge: '2.4rem',
    huge: '2.8rem',
    xhuge: '3.2rem',
  },
  margins: {
    xsmall: '0.4rem',
    small: '0.8rem',
    medium: '1.2rem',
    large: '1.6rem',
    xlarge: '2rem',
    xxlarge: '2.4rem',
    huge: '2.8rem',
    xhuge: '3.2rem',
  },
  spacings: {
    xsmall: '8rem',
    small: '1.6rem',
    medium: '2.4rem',
    large: '3.2rem',
    xlarge: '4.0rem',
    xxlarge: '4.8rem',
    huge: '5.6rem',
    xhuge: '6.4rem',
  },
};
